### ISSUE TITLE
Ra break for Consterllation Hydra

### ISSUE THREAD

**Issue by oxno2** [pmelchior/skymapper#26]
Hi, I try to use Skymapper to draw the constellation Hydra, but I found for this constellation, there is a break in RA. I think the problem might be there is a break for RA value at RA=180. Are there any methods for me to correct this?
![7](https://user-images.githubusercontent.com/22302177/62841197-8d054980-bc6a-11e9-9aa9-0423b721d1f1.png)

Also, when I draw the constellation Ursa Major, there is a projection problem. I want to rotate the graph to left by 90 degrees and revert the direction of texts.  Are there any methods to do this?

![8](https://user-images.githubusercontent.com/22302177/62841220-e8373c00-bc6a-11e9-9105-8cecb23c31a1.png)

**Comment by pmelchior** [comment]
You can define any projection with a lon_0 argument, which defines the RA in the middle of the map. It's generally best to adjust the projection so that what you care about is in the middle.

I am not sure what you want to do in the second example, but you can adjust the rotation of the text to follow meridians or parallels, or simply set rotation=0 for horizontal.
