### ISSUE TITLE
polygons need to be split when extending beyond the antimeridian

### ISSUE THREAD

**Issue by rainwoodman** [pmelchior/skymapper#7]
When ra spans a wide range.

![index](https://cloud.githubusercontent.com/assets/138060/13861361/86357648-ec52-11e5-971f-885b9003fc6c.png)

**Comment by rainwoodman** [comment]
This is actually due to the periodic wrapping..

**Comment by pmelchior** [comment]
It turns out this cut is routinely done in mapping software these days: http://bl.ocks.org/mbostock/3788999

If we restrict ourselves the cases where ra_0 is fixed, we only have to do this once and changes to xlim will not matter.

What is therefore needed is a method that takes in vertex coordinates for simple polygons and
1. detects if they cross the antimeridian (e.g. in the west), and if so:
2. modifies the inner part of each polygon detected in 1) to follow the western antimeridian
3. for the remaining nodes of the polygon: move them to ra - 360, and close the patch to follow the eastern antimeridian.

From the code we have right now, these operations must be done in the RA/Dec frame because the periodic wrapping from the tranformation causes the problem. That means we cannot do it in map coordinates.

One immediate consequence of this splitting is that we need to make sure the collections of vertices can have an arbitrary length. Even healpix tetragons can have between 3 and 5 vertices after the split.

That means we need to rework https://github.com/pmelchior/skymapper/blob/master/skymapper.py#L735

**Comment by rainwoodman** [comment]
I think what I've done in PR #8 in somewhat along these lines. It is much simpler because I simply shift all vertices to the same periodicity. 

Some vertices near the edge will be missing -- as a first fix it is good enough I guess. 

It is actually very easier to do this in transform_path() function.

**Comment by pmelchior** [comment]
It would still be good not to loose any patches, but this is solving the biggest issue. Closed.
